### ISSUE TITLE
BUG: Buying a gift membership ends current membership (only Paypal Gateway)

### ISSUE THREAD

**Issue by greathmaster** [strangerstudios/pmpro-gift-levels#11]

**Comment by codyrickman** [comment]
I can confirm this is an issue when using Paypal Express as a checkout method. The user buying the "Gift Subscription" gets that level set as their current membership level. This is a major issue on my site as that means they lose access to all features.  Is there a fix for this? Much appreciated!

**Comment by andrewlimaza** [comment]
This has been fixed and merged in the dev branch. You may pull the latest pre-release from here -https://github.com/strangerstudios/pmpro-gift-levels
