### ISSUE TITLE
Conflicts with proration plugin

### ISSUE THREAD

**Issue by humbabba** [strangerstudios/pmpro-gift-levels#15]
It appears that if I have both this and the proration plugin (https://github.com/strangerstudios/pmpro-proration) installed that the price of the gift account gets my paid balance assigned to it as if I'm changing levels for myself. 

This is with Stripe as the payment gateway. 

Example:

I have an annual membership at $10, just bought, so I've only used $1 worth of it and have $9 worth of the year membership to go. 

I go to by a $5 gift membership.

The checkout page doesn't ask for my payment info since I still have $9 in the bank, so to speak.

**Comment by dparker1005** [comment]
This would require adding a filter to unhook the proration add on if the user is checking out for a gift level.

**Comment by kimwhite** [comment]
Any ideas if this will ever be compatible?

**Comment by kimcoleman** [comment]
With PMPro 3.0+ and level groups, we now recommend that your Gift Levels are all in one group that would not conflict with your main level groups. Proration is designed to only prorate within the level group so this should no longer be an issue.
