### ISSUE TITLE
Feature: Show which user bought discount code and Show on user's admin profile too.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-gift-levels#18]
Site owners would like to see who purchased specific codes.

The Gift Giver can see the code they bought and when it's redeemed on their Account Page, but there is no way for ADMIN to see this relationship.

Ways to do this:
Add the Gift Code information to the admin area profile.
Add the Gift Code to the Giver's order.
Add Giver's username to Discount Code info.

**Comment by dparker1005** [comment]
At the very least, I think adding the gift code to order meta makes a lot of sense. Adding to the "Edit User" page would also be nice.
