### ISSUE TITLE
Why discount start date is set to yesterday?

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/pmpro-gift-levels#21]
I refer to this one: https://github.com/strangerstudios/pmpro-gift-levels/blob/b4bc85ecff457287f80fbede5d8a6982383b46c8/pmpro-gift-levels.php#L94

Maybe because otherwise the code is not valid today if generated today?

I think this is so much misleading and complicates things.

**Comment by mircobabini** [comment]
I see this change is from a pull request https://github.com/strangerstudios/pmpro-gift-levels/commit/9dbaf8b013abcb57c775f8e254d03fd6111bb721

But was not reported what was wrong with it.

**Comment by dparker1005** [comment]
> Maybe because otherwise the code is not valid today if generated today?
I believe you are correct here. We want to make sure that the code is able to be used immediately. We should add a comment in the code to clarify that.
