### ISSUE TITLE
Cannot find the option in Advanced settings

### ISSUE THREAD

**Issue by iammalen** [strangerstudios/pmpro-gift-levels#3]
Hi,

I installed the plugin for the Manager role however there were no options added in the Advance settings.
http://www.paidmembershipspro.com/add-ons/plugins-on-github/pmpro-membership-manager-role/
screenshot --> http://snag.gy/hRlnw.jpg

**Comment by andrewlimaza** [comment]
This is an outdated issue not relating to Gift Levels Add On. If you have any further questions relating to Paid Memberships Pro, please open up a ticket on www.paidmembershipspro.com
