### ISSUE TITLE
Call to undefined function pmpro_getAllLevels

### ISSUE THREAD

**Issue by knit-pay** [strangerstudios/pmpro-gift-levels#52]
**Describe the bug**
website crashed if plugin installed without installing paid memberships pro plugin

Fatal error: Uncaught Error: Call to undefined function pmpro_getAllLevels() in /var/www/dev/wp-content/plugins/pmpro-gift-levels-dev/includes/functions.php on line 14

**To Reproduce**
website crashed if plugin installed without installing paid memberships pro plugin

**Comment by dparker1005** [comment]
Thank you for this bug report, @knit-pay. I have just created a commit to address this here:
https://github.com/strangerstudios/pmpro-gift-levels/commit/f7307b5d3ee9aca7be0938195ba411da3ed630b6
