### ISSUE TITLE
Gift Discount Code $start times

### ISSUE THREAD

**Issue by sknishizaki** [strangerstudios/pmpro-gift-levels#6]
The code to generate a new discount code when a gift membership is purchased uses the current time and doesn't appear to take into account the GMT offset.  This leads to codes that "aren't active" being sent out.  I modified with $starts = date("Y-m-d", strtotime("-1 day")) just to really be safe.

**Comment by greathmaster** [comment]
Applied this suggestion as part of https://github.com/strangerstudios/pmpro-gift-levels/pull/9

**Comment by andrewlimaza** [comment]
This has been merged into the latest dev branch, you can grab a pre-release from here - https://github.com/strangerstudios/pmpro-gift-levels
