### ISSUE TITLE
Level id no longer in email link

### ISSUE THREAD

**Issue by robwent** [strangerstudios/pmpro-gift-levels#7]
Has anything changed recently that might affect the link sent in the email from here?

https://github.com/strangerstudios/pmpro-gift-levels/blob/master/pmpro-gift-levels.php#L307

I'm not sure when it broke but links are now coming through in the email like this:

    membership-checkout/?level=&discount_code=G8837867FCC

I had a similar issue in a customisation plugin that was sorting the level order using  the `pmpro_levels_array` filter recently and ended up just moving the same logic to the template file.

Could it be related to the drag and drop for level ordering?

**Comment by robwent** [comment]
It looks like the codes being sent are also wrong. The one in the link above from a test purchase was generated in 2014 (the 6th one ever created), not the one actually generated during the purchase.

**Comment by andrewlimaza** [comment]
Tested this and it works as intended, if you are still having issues with this please reach out on www.paidmembershipspro.com
